apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wso2esb
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: wso2esb
    spec:
      containers:
      - name: wso2esb
        image: isim/wso2esb
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: wso2esb
spec:
  ports:
  - port: 9443
  selector:
    app: wso2esb
  type: LoadBalancer
